name: Team awesome's approval workflow
on: pull_request_review
  jobs:
    labelWhenApproved:
      runs-on: ubuntu-latest
        steps:
        - name: LabelingWhenDone
        - uses: pullreminders/label-when-approved-action@team-workflow
          env:
            APPROVALS: "1"
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ADD_LABEL: "Done"
